/**
 * Cláusulas legais fixas dos formulários ASLAM (texto literal dos PDFs de referência).
 */

export const ASLAM_MINOR_CLAUSES = `1) O RESPONSÁVEL e/ou MENOR/ATLETA declara(m) ter conhecimento de que o atleta para participar das aulas de Jiu-Jitsu deverá ter mais de 07 anos ( sete anos ), bem como de que a prática desportiva envolve testes físicos, treinamentos coletivos e qualquer outro tipo de trabalho técnico e/ou físico necessário à preparação prática esportiva.

2) O RESPONSÁVEL e/ou MENOR/ATLETA declara(m) estar ciente de que, como em qualquer outra atividade física, podem ocorrer lesões e ferimentos no ATLETA durante as aulas e treinos, sendo que nenhuma responsabilidade será atribuída a Associação de Lutas e Artes Marciais - ASLAM.

3) Sendo desejo do MENOR/ATLETA e RESPONSÁVEL que o primeiro participe dos treinos e aulas a serem realizadas, ambos isentam a Associação de Lutas e Artes Marciais - ASLAM, de toda e qualquer responsabilidade por eventuais lesões físicas, fraturas, acidentes em geral ou danos de qualquer natureza que venham a ocorrer no desenvolvimento das atividades físicas durante as aulas e treinos.

4) Concordo também efetuar os pagamentos de mensalidades sugeridos pela ASLAM até o dia 10 de cada mês, concordando e assumindo as consequências pelo não cumprimento do acordo.`;

export const ASLAM_ADULT_CLAUSES = `DECLARO, concordo e assumo qualquer responsabilidade pelos acidentes pessoais, que possam vir a ocorrer nos treinos e/ou competições da Associação de Lutas e Artes Marciais – ASLAM, isentando completamente a academia (ASLAM) , da responsabilidade de ressarcimentos por qualquer tipo de dano à pessoa ou propriedade, oriundos da prática dos treinos oferecidos pela Associação de Lutas e Artes Marciais – ASLAM. Reconheço e assumo, livremente, todos os riscos conhecidos, ou não, que possam ocorrer durante os treinos e entendo que, como qualquer outra atividade física a prática dos esportes oferecidos pela ASLAM, possui risco de acidente, como lesões, fraturas, quedas, torções, estrangulamentos, luxações e estiramentos e assumo total responsabilidade pela minha participação . Como participante, assumo toda e qualquer consequência de meus atos no período de duração das atividades e naquele que antecede e o sucede, bem como meu trajeto até o local da pratica do esporte e saída de lá, também me prontifico a obedecer e respeitar o Professor da ASLAM enquanto durar a atividade, por motivos de segurança. Autorizo, ainda, o eventual uso de minha imagem, em caso de ser colhida durante os treinos e/ou competições do mencionado esporte, renunciando a qualquer remuneração ou indenização. Autorizo também, em caso de lesões e/ou mal estar físico, que os membros e/ou Professor da ASLAM contate o Serviço de Atendimento Médico - SAMU ou qualquer outro serviço de atendimento de emergência, assim como realizar em mim todos os procedimentos diagnósticos necessários para tal atendimento. Concordo também efetuar os pagamentos de mensalidades sugeridos pela ASLAM até o dia 10 de cada mês, concordando e assumindo as consequências pelo não cumprimento do acordo. APÓS TER LIDO E COMPREENDIDO ESTE TERMO DE RESPONSABILIDADE, DECLARO E CONFIRMO ESTAR DE PLENO ACORDO COM TODO O TEOR DO DOCUMENTO. O QUE FAÇO DE LIVRE E VOLUNTARIAMENTE, SEM QUALQUER COERÇÃO.`;
